---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: postgres-idp
  name: postgres-idp
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: postgres-idp
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: postgres-idp
    spec:
      containers:
        - name: postgres-idp
          image: postgres:15.5
          resources: {}
          env:
            - name: POSTGRES_DB
              value: keycloak
            - name: POSTGRES_USER
              value: keycloak
            - name: POSTGRES_PASSWORD
              value: password
          volumeMounts:
            - mountPath: /var/lib/postgresql-idp/data
              name: postgres-idp-claim1
            - mountPath: /pg-idp/backups
              name: postgres-idp-claim2
      imagePullSecrets:
        - name: teadal-registry-secret
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
        - name: postgres-idp-claim1
          persistentVolumeClaim:
            claimName: postgres-idp-claim1
        - name: postgres-idp-claim2
          persistentVolumeClaim:
            claimName: postgres-idp-claim2
status: {}
