dags:
  persistence:
    storageClassName: microk8s-hostpath
    size: 1Gi

logs:
  persistence:
    storageClassName: microk8s-hostpath
    size: 1Gi

workers:
  persistence:
    storageClassName: microk8s-hostpath
    size: 1Gi

triggerer:
  persistence:
    storageClassName: microk8s-hostpath
    size: 1Gi

redis:
  persistence:
    storageClassName: microk8s-hostpath
    size: 1Gi

postgresql:
  primary:
    persistence:
      storageClass: microk8s-hostpath
