apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- base.yaml

configMapGenerator:
#- name: kcong-realm-bootstrap
#  files:
#  - kcong-bootstrap.json
- name: keycloak-configmap
  files:
  - kcong-bootstrap.json
  - teadal-bootstrap.json

