apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- project.yaml
- argocd
- postgres
# - directpv
# - grafana
# - jaeger
- keycloak
# - kiali
- minio
- opa
- prometheus
- pvc
- reloader
- routing
- sc
# - kepler
