type: S3
config:
  bucket: "thanos-bucket"           # Nome del bucket MinIO
  endpoint: "teadal-teadal-0.teadal-hl.minio-operator.svc.cluster.local:9000"  # Endpoint del servizio MinIO
  access_key: KN335GF5J0GA104HMH4S 
  secret_key: RjLJSEHwPmgBtkDbuqoDiQ9E44UKl6F4NtOU1jpM  
  insecure: true                   # Usa `true` se non stai usando HTTPS
