apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: "teadal-gateway"
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - "*"
    port:
      name: http
      number: 80
      protocol: HTTP
  # - hosts:
  #   - "*"
  #   port:
  #     name: http_catalogue
  #     number: 8000
  #     protocol: HTTP
  - hosts:
    - "*"
    port:
      name: postgres
      number: 5432
      protocol: TCP
  - hosts:
    - "*"
    port:
      name: advocate
      number: 8000
      protocol: TCP 
  - hosts:
    - "*"
    port:
      name: kubeflow
      number: 3810
      protocol: HTTP
  - hosts:
    - "*"
    port:
      name: catalogue-minio
      number: 9000
      protocol: HTTP
  - hosts:
    - "*"
    port:
      name: dspn-diagrameditor
      number: 5173
      protocol: HTTP
  - hosts:
    - "*"
    port:
      name: ollama
      number: 11434
      protocol: HTTP

