schema = 3

[mod]
  [mod."github.com/cpuguy83/go-md2man/v2"]
    version = "v2.0.2"
    hash = "sha256-OvWCtDsVrYzM84SMQwOXPLBxnWnMC1hDm+KiI6zm3uk="
  [mod."github.com/davecgh/go-spew"]
    version = "v1.1.1"
    hash = "sha256-nhzSUrE1fCkN0+RL04N4h8jWmRFPPPWbCuDc7Ss0akI="
  [mod."github.com/emicklei/go-restful/v3"]
    version = "v3.11.0"
    hash = "sha256-Kp5ndPvj1PhK0nscM1pNNK2Q4ahUuLED/baEgL9pKNo="
  [mod."github.com/evanphx/json-patch"]
    version = "v4.12.0+incompatible"
    hash = "sha256-rUOokb3XW30ftpHp0fsF2WiJln1S0FSt2El7fTHq3CM="
  [mod."github.com/evanphx/json-patch/v5"]
    version = "v5.6.0"
    hash = "sha256-9P31eky/JuDLlVmKUk4+SfoXWLuJqANm5gSMDzR82No="
  [mod."github.com/go-logr/logr"]
    version = "v1.3.0"
    hash = "sha256-N8JYtQlwpLWTaCczfhfA/YmHExko0ObPMYVGw8JwbSw="
  [mod."github.com/go-openapi/jsonpointer"]
    version = "v0.19.6"
    hash = "sha256-C/ICmPQu0faBiZ/qCHoy6Nzyy2FDO5QiahzlXSCwvIw="
  [mod."github.com/go-openapi/jsonreference"]
    version = "v0.20.2"
    hash = "sha256-klWZKK7LZqSg3HMIrSkjh/NwaZTr+8kTW2ok2+JlioE="
  [mod."github.com/go-openapi/swag"]
    version = "v0.22.3"
    hash = "sha256-iUGFBMt9RobFG+Qsy2zKWEjFARi2xCSCaV2HRDL0vw4="
  [mod."github.com/gogo/protobuf"]
    version = "v1.3.2"
    hash = "sha256-pogILFrrk+cAtb0ulqn9+gRZJ7sGnnLLdtqITvxvG6c="
  [mod."github.com/golang/protobuf"]
    version = "v1.5.3"
    hash = "sha256-svogITcP4orUIsJFjMtp+Uv1+fKJv2Q5Zwf2dMqnpOQ="
  [mod."github.com/google/gnostic-models"]
    version = "v0.6.8"
    hash = "sha256-YzA/XpvPyfdplJtHmAUdQk9P+j0NBwHhW9nj1DaGaoQ="
  [mod."github.com/google/gofuzz"]
    version = "v1.2.0"
    hash = "sha256-T6Gz741l45L3F6Dt7fiAuQvQQg59Qtap3zG05M2cfqU="
  [mod."github.com/google/uuid"]
    version = "v1.3.0"
    hash = "sha256-QoR55eBtA94T2tBszyxfDtO7/pjZZSGb5vm7U0Xhs0Y="
  [mod."github.com/gorilla/websocket"]
    version = "v1.5.0"
    hash = "sha256-EYVgkSEMo4HaVrsWKqnsYRp8SSS8gNf7t+Elva02Ofc="
  [mod."github.com/imdario/mergo"]
    version = "v0.3.15"
    hash = "sha256-HyN1PxCZW2IRns9VDkwxMHtDvdDwaRgat0wcHf53B0w="
  [mod."github.com/josharian/intern"]
    version = "v1.0.0"
    hash = "sha256-LJR0QE2vOQ2/2shBbO5Yl8cVPq+NFrE3ers0vu9FRP0="
  [mod."github.com/json-iterator/go"]
    version = "v1.1.12"
    hash = "sha256-To8A0h+lbfZ/6zM+2PpRpY3+L6725OPC66lffq6fUoM="
  [mod."github.com/mailru/easyjson"]
    version = "v0.7.7"
    hash = "sha256-NVCz8MURpxgOjHXqxOZExqV4bnpHggpeAOyZDArjcy4="
  [mod."github.com/moby/spdystream"]
    version = "v0.2.0"
    hash = "sha256-Feme5UoWuBCvnLPKw1ozKkF3SM7PAjjPFQZ3TJhghR0="
  [mod."github.com/modern-go/concurrent"]
    version = "v0.0.0-20180306012644-bacd9c7ef1dd"
    hash = "sha256-OTySieAgPWR4oJnlohaFTeK1tRaVp/b0d1rYY8xKMzo="
  [mod."github.com/modern-go/reflect2"]
    version = "v1.0.2"
    hash = "sha256-+W9EIW7okXIXjWEgOaMh58eLvBZ7OshW2EhaIpNLSBU="
  [mod."github.com/munnerz/goautoneg"]
    version = "v0.0.0-20191010083416-a7dc8b61c822"
    hash = "sha256-79URDDFenmGc9JZu+5AXHToMrtTREHb3BC84b/gym9Q="
  [mod."github.com/mxk/go-flowrate"]
    version = "v0.0.0-20140419014527-cca7078d478f"
    hash = "sha256-gRTfRfff/LRxC1SXXnQd2tV3UTcTx9qu90DJIVIaGn8="
  [mod."github.com/pkg/errors"]
    version = "v0.9.1"
    hash = "sha256-mNfQtcrQmu3sNg/7IwiieKWOgFQOVVe2yXgKBpe/wZw="
  [mod."github.com/russross/blackfriday/v2"]
    version = "v2.1.0"
    hash = "sha256-R+84l1si8az5yDqd5CYcFrTyNZ1eSYlpXKq6nFt4OTQ="
  [mod."github.com/spf13/pflag"]
    version = "v1.0.5"
    hash = "sha256-w9LLYzxxP74WHT4ouBspH/iQZXjuAh2WQCHsuvyEjAw="
  [mod."github.com/urfave/cli/v2"]
    version = "v2.27.1"
    hash = "sha256-L+Z9fYABYg7KiB57MK64+XcXEWNjP04WWpjbENOxPWY="
  [mod."github.com/vladimirvivien/gexe"]
    version = "v0.2.0"
    hash = "sha256-aJ4OqAs2zuV41oj4p2u8aohUAm/gTQYrDXo5nMPxehw="
  [mod."github.com/xrash/smetrics"]
    version = "v0.0.0-20201216005158-039620a65673"
    hash = "sha256-WGHtW/OkLowkqOYIvXpDOpn9wqdH2+Dyx3+rYwpmvzI="
  [mod."golang.org/x/crypto"]
    version = "v0.18.0"
    hash = "sha256-BuMVUxOIyfLo8MOhqYt+uQ8NDN6P2KdblKyfPxINzQ4="
  [mod."golang.org/x/net"]
    version = "v0.19.0"
    hash = "sha256-3M5rKEvJx4cO/q+06cGjR5sxF5JpnUWY0+fQttrWdT4="
  [mod."golang.org/x/oauth2"]
    version = "v0.10.0"
    hash = "sha256-fKUwQ8HPEP4y6ZAtNHHHMDMYn2Fo6qTMcY45BbpE+Eg="
  [mod."golang.org/x/sys"]
    version = "v0.16.0"
    hash = "sha256-ZkGclbp2S7NQYhbuGji6XokCn2Qi1BJy8dwyAOTV8sY="
  [mod."golang.org/x/term"]
    version = "v0.16.0"
    hash = "sha256-9qlHcsCI1sa7ZI4Q+fJbOp3mG5Y+uV16e+pGmG+MQe0="
  [mod."golang.org/x/text"]
    version = "v0.14.0"
    hash = "sha256-yh3B0tom1RfzQBf1RNmfdNWF1PtiqxV41jW1GVS6JAg="
  [mod."golang.org/x/time"]
    version = "v0.3.0"
    hash = "sha256-/hmc9skIswMYbivxNS7R8A6vCTUF9k2/7tr/ACkcEaM="
  [mod."google.golang.org/appengine"]
    version = "v1.6.7"
    hash = "sha256-zIxGRHiq4QBvRqkrhMGMGCaVL4iM4TtlYpAi/hrivS4="
  [mod."google.golang.org/protobuf"]
    version = "v1.31.0"
    hash = "sha256-UdIk+xRaMfdhVICvKRk1THe3R1VU+lWD8hqoW/y8jT0="
  [mod."gopkg.in/inf.v0"]
    version = "v0.9.1"
    hash = "sha256-z84XlyeWLcoYOvWLxPkPFgLkpjyb2Y4pdeGMyySOZQI="
  [mod."gopkg.in/yaml.v2"]
    version = "v2.4.0"
    hash = "sha256-uVEGglIedjOIGZzHW4YwN1VoRSTK8o0eGZqzd+TNdd0="
  [mod."gopkg.in/yaml.v3"]
    version = "v3.0.1"
    hash = "sha256-FqL9TKYJ0XkNwJFnq9j0VvJ5ZUU1RvH/52h/f5bkYAU="
  [mod."k8s.io/api"]
    version = "v0.29.1"
    hash = "sha256-VgKBCy7mIi0U6SxhY4WA7bCMuC/pMnOi1ESjazIGcPs="
  [mod."k8s.io/apimachinery"]
    version = "v0.29.1"
    hash = "sha256-TU0woi326oyFjYvGbtROtZMaZPJo+aGdpu8HSdZfUZc="
  [mod."k8s.io/client-go"]
    version = "v0.29.1"
    hash = "sha256-rM/CUCAO6erS3GnR2XE5W/RhMDhL9ZlaX7h4HJyLU/U="
  [mod."k8s.io/klog/v2"]
    version = "v2.110.1"
    hash = "sha256-0nmkyVd1B4lnCLsPxtdJWDZW4EGOwcgYXnA6M9j01ss="
  [mod."k8s.io/kube-openapi"]
    version = "v0.0.0-20231010175941-2dd684a91f00"
    hash = "sha256-mEf/01LBDSVhJIuIIHI7BYjqO1j01BGR6KOYNvIbznU="
  [mod."k8s.io/utils"]
    version = "v0.0.0-20230726121419-3b25d923346b"
    hash = "sha256-r8VhhAYGPouGGgXu02ymVwF6k+WmBc4ij0qynPRtXEE="
  [mod."sigs.k8s.io/controller-runtime"]
    version = "v0.15.1"
    hash = "sha256-1y2kEntsTwfiLWTTwYpTX5KZA3hBB9ze4Cj1PBYfDMA="
  [mod."sigs.k8s.io/e2e-framework"]
    version = "v0.3.0"
    hash = "sha256-yDPaeIfHBpGG5mO8YPeSW2+ZRT/W0I4WJpMypgmlOGo="
  [mod."sigs.k8s.io/json"]
    version = "v0.0.0-20221116044647-bc3834ca7abd"
    hash = "sha256-XDBMN2o450IHiAwEpBVsvo9e7tYZa+EXWrifUNTdNMU="
  [mod."sigs.k8s.io/structured-merge-diff/v4"]
    version = "v4.4.1"
    hash = "sha256-FcZHHZCKNNZW6/s1T1sKiS5Vj1TpHPmxVWr6YlL60xA="
  [mod."sigs.k8s.io/yaml"]
    version = "v1.3.0"
    hash = "sha256-RVp8vca2wxg8pcBDYospG7Z1dujoH7zXNu2rgZ1kky0="
