apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- project.yaml
- httpbin
# - catalogue
- dspn-diagrameditor
- opa-policy-manager
# - redis/app.yaml
# - ollama
# - fdp-sync-dummy
# - sfdp-sync-dummy
