apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- teadal-test-node-1.yaml
- teadal-test-node-2.yaml
- teadal-test-node-3.yaml
- teadal-test-node-4.yaml
- teadal-test-node-5.yaml
- teadal-test-node-6.yaml
- teadal-test-node-7.yaml
- teadal-test-node-8.yaml
- teadal-test-node-9.yaml
