apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: blazegraph
  name: blazegraph
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: blazegraph
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: blazegraph
    spec:
      containers:
      - env:
        - name: JAVA_OPTS
          value: ' -Dfile.encoding=UTF-8 -Dsun.jnu.encoding=UTF-8 '
        image: nawer/blazegraph
        imagePullPolicy: ""
        name: blazegraph
        resources: {}
        volumeMounts:
        - mountPath: /var/lib/blazegraph
          name: blazegraph-claim0
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: blazegraph-claim0
        persistentVolumeClaim:
          claimName: blazegraph-claim0
status: {}
