apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


resources:
#- prometheus.yaml
- node-exporter-daemonset.yaml
- prometheus-thanos.yaml
#- https://raw.githubusercontent.com/istio/istio/1.18.0/samples/addons/prometheus.yaml
