apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  istio-injection: enabled
  zone: "sharing"
resources:
- httpbin/
- catalogue/
- dspn-diagrameditor
- opa-policy-manager
# - redis
# - ollama
# - fdp-sync-dummy
# - sfdp-sync-dummy
 
